### ISSUE TITLE
RetrieveRecordedRequests failed to deserialize HttpRequest array

### ISSUE THREAD

**Issue by omer-za** [picadoh/mockserver-client-csharp#11]
I get the following error when trying to get recorded requests from the mock server using docker container latest version (5.11.2)

_Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: {. Path '[0].body.json', line 7, position 14_

My assumption is a problem with the HttpRequest object "body" JsonProperty definition.

**Comment by picadoh** [comment]
Apologies for the delay. This project has been stale for some time. All dependencies including .NET itself are now updated (version `2.x.x`), which should fix this issue. Please reopen the issue if the problem persists.

**Comment by BeeHiveJava** [comment]
Getting exactly the same error on the latest version. Sorry to dig this up if you're no longer working on this project @picadoh. 

MockServer is responding with a json object:
```JSON
"json": {
  "content": "{}"
}
```

When the deserialization code expects a string: https://github.com/picadoh/mockserver-client-net/blob/0ebe7436d9821db2294575c93be1618461f803ac/src/MockServerClientNet/Model/Body/Body.cs#L22
