### ISSUE TITLE
Support for required headers?

### ISSUE THREAD

**Issue by dposada** [picadoh/mockserver-client-csharp#13]
Is there a way to specify that a particular header key/value pair is required?

**Comment by picadoh** [comment]
Mock-Server (server side) has built-in support for that using regex at the header level. Here's an example using this C# client using the "WithHeader" builder method:

```csharp
var mockServerClient = new MockServerClient("127.0.0.1", 1080);

await mockServerClient.ResetAsync();

await mockServerClient
    .When(Request()
        .WithMethod(HttpMethod.Get)
        .WithPath("/hello")
        .WithHeader("Mandatory-Header", "SomeValue"),
        Times.Unlimited())
    .RespondAsync(Response().WithStatusCode(200).WithBody("Hello World!"));
```

A wildcard can be used if value is irrelevant, e.g., `.WithHeader("Mandatory-Header", ".*")`.
