### ISSUE TITLE
Support for mockserver.tlsMutualAuthenticationRequired=true

### ISSUE THREAD

**Issue by michalcernik** [picadoh/mockserver-client-csharp#6]
Hi,
to:  hugo.pcd@gmail.com.
I would like to use this package for scenarios when MockServer requires mutual certificate authentication. According to the code, it neither supports using the MockServer API over https, nor can it use a client certificate for authentication.
Changes required:
- extend AbstractClient and MockServerClient with few properties (bool useTls, X509Certificate2 clientCertificate - or friendly name, store name and location), also their constructors with arguments
- extend WithPath extension method to enable https protocol when required
- extend AbstractClient.SendRequestAsync so that httpClient uses the certificate when required

Should you find the idea useful, I am willing to make the code changes.

Regards

Michal Cernik

**Comment by picadoh** [comment]
Implemented on commit e25aa9391ad5a084677b4c821a41c97e6b3f0df0.
